[package]
name = "mm0-rs"
version = "0.1.0"
authors = ["Mario Carneiro <di.gama@gmail.com>"]
edition = "2018"
description = "MM0/MM1 language toolchain"
repository = "https://github.com/digama0/mm0"
readme = "README.md"
license = "CC0"
keywords = ["theorem", "proving", "proof", "assistant"]
categories = ["command-line-utilities", "development-tools", "mathematics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["server", "doc"]
server = ["lsp-types", "lsp-server", "crossbeam", "simplelog", "log"]
doc = ["pulldown-cmark"]
memory = ["deepsize_derive/nodummy"]
wasm = ["console_error_panic_hook", "wasm-bindgen", "web-sys"]

[profile.release]
debug = true

[dependencies]
either = "1.6.1"
owning_ref = "0.4.1"
bitflags = "1.2.1"
byteorder = "1.3.4"
lazy_static = "1.4.0"
itertools = "0.9.0"
pathdiff = "0.2.0"
num = "0.3.1"
typed-arena = "2.0.1"
pretty = "0.10.0"
clap = "2.33.3"
futures = { version = "0.3.8", features = ["thread-pool"] }
serde = "1.0.117"
serde_json = "1.0.59"
serde_repr = "0.1.6"
annotate-snippets = { version = "0.9.0", features = ["color"] }
libc = "0.2.80"
zerocopy = "0.3.0"
memchr = "2.3.4"
bit-set = "0.5.2"
deepsize_derive = { path = "components/deepsize_derive", default-features = false }
debug_derive = { path = "components/debug_derive" }

# For "server" feature
log = { version = "0.4.11", optional = true }
simplelog = { version = "0.8.0", optional = true }
crossbeam = { version = "0.8.0", optional = true }
lsp-types = { version = "0.83.1", optional = true }
lsp-server = { version = "0.5.0", optional = true }

# For "doc" feature
pulldown-cmark = {version = "0.8.0", optional = true }

# For "wasm" feature
console_error_panic_hook = { version = "0.1.6", optional = true }
wasm-bindgen = { version = "0.2.69", optional = true }
web-sys = { version = "0.3.46", features = ["console", "Window", "Document", "HtmlElement"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = "0.4.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
memmap = "0.7.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[[bin]]
name = "mm0-rs"
path = "src/main.rs"
doc = false