[package]
name = "mm0-rs"
version = "0.1.0"
authors = ["Mario Carneiro <di.gama@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.5.3"
owning_ref = "0.4.0"
bitflags = "1.2.1"
lazy_static = "1.4.0"
itertools = "0.8.2"
num = "0.2.0"
log = "0.4.8"
simplelog = "0.7.4"
crossbeam = "0.7.3"
futures = { version = "0.3.1", features = ["thread-pool"] }
serde = "1.0.103"
serde_json = "1.0.42"
lsp-types = "0.61.0"
lsp-server = "0.3.0"