brace_style = "SameLineWhere"
fn_args_layout = "Compressed"
fn_single_line = true
match_arm_blocks = false
trailing_semicolon = false
use_field_init_shorthand = true
where_single_line = true
tab_spaces = 2